### ISSUE TITLE
Manage replication (no auth)

### ISSUE THREAD

**Issue by pelzerim** [unumotors/mongo-hydra#10]
- Take list of hostnames and apply it
Initiate replica set 

- CI needs to support multiple mongod instances to apply (need to start with different command)
- make sure mongo client is connected to a master (wrapper around 3 clients and find the master)

prerequisites: 3 uninitialized repicas
1. hyrda replica -r -r -r initialize it
2. hyrda replica -r -r remove a replica
3. hyrda replica -r -r -r add a replica

[edit] removed these from scope:

Add a member
Remove a member

**Comment by pelzerim** [comment]
> CI needs to support multiple mongod instances to make this happen (need to start with different command)

This is also an issue locally.  We need a local setup that developers can test against. (multiple different mongod instances running with different setup)

Tilt or docker-compose? 

Docker-compose is nice and simple but will need replacement when this might turn into an operator. Tilt is powerful but will likely take a while to get running.

**Comment by drubin** [comment]
> Tilt or docker-compose?

My crazy idea was to provide both, this way users can see how things work across different providers (this is the power of hydra) 

FFor example having example directory and having different configurations hydra and docker-compose and k8s for all the different architecture we support.



But for now, I say pick (one) whichever is easier, the ideas that we are just using them as external endpoints, we don't plan on running this thing inside the tilt/docker-compose for now at least (that will slow things down)

So docker-compose for now.

**Comment by drubin** [comment]
for CI I thought of just adding multiple services on different ports, but I can't seem to find an  option to change the entry point of the service  in github actions.

**Comment by pelzerim** [comment]
> So docker-compose for now.

I agree.

> for CI I thought of just adding multiple services on different ports, but I can't seem to find an option to change the entry point of the service in github actions.

This would require for example replica sets to have different ports inside the same replica set. I do not know if mongo even supports this, this would at least be an anti-pattern.

**Comment by drubin** [comment]
> This would require for example replica sets to have different ports inside the same replica set. I do not know if mongo even supports this, this would at least be an anti-pattern.

It will. via the port. BUT this library is supposed to be about best practises so lets leave it for now, but I do think basing choices based on port number seems risky.

but let's leave it off, for now, it would just have made testing easier to be able to run multiple mongo instances on the same host

**Comment by drubin** [comment]
`mongod --port 23456` this works for example

What I mean is this would have allowed you to test all this without even running docker and also in CI.

**Comment by pelzerim** [comment]
>What I mean is this would have allowed you to test all this without even running docker and also in CI.

If it required for makeing testing work, i will add it
